<p ><img style="float:left" src="ME_AEFHP_unesco2.png"></p> 

#### <p ><img style="float:right" src="Python-Logo2.png"></p> 
# <font color="DarkSlateBlue">UFCD 10793 - Fundamentos de Python</font>
## <font color="MidnightBlue">Notebook 05 - Trabalhar com arrays em Python</font> 
### <font color="MidnightBlue">Sílvia Martins</font> 
### <font color="MidnightBlue">AEFHP 2022</font> 

### <font color="FireBrick"> Vetores e matrizes</font> 
O Python não contém uma estrutura nativa para a representação explícita de `arrays`,  a <b>linguagem aplica as mesmas instruções associadas às listas para manipular arrays</b>.

Os vetores e matrizes em Python são criados e manipulados através da estrutura de dados lista encadeada (`list`).
Um vetor é representado por uma lista e, uma matriz, é representada por uma lista de listas (a lista das suas linhas), todas com o mesmo comprimento. 
Não esquecer que os arrays, por definição, armazenam valores do mesmo tipo.

No NB 04.10793 - Listas pudeste observar como trabalhar com listas e usar algumas dos seus métodos o que corresponderia a um vetor, sempre que os elementos fossem do mesmo tipo.



Gerar uma matriz de 4 linhas e 3 colunas e imprimi-la por linhas:

In [1]:
A=[[x, y] for x in range(1,3) for y in range(1,2)]
print(f"Matriz ({len(A)}x{len(A[0])}):")
print(A)
for i in range (0,len(A)):
    for j in range(0, len(A[i])):
        print (f"{A[i][j]:3d}\t", end="")
    print()

Matriz (2x2):
[[1, 1], [2, 1]]
  1	  1	
  2	  1	


Gerar uma matriz V de 2X2 ,  de inteiros fornecidos pelo utilizador (usando o método `append`):

In [6]:
M = []
for i in range(2):
    linha = []                  # inicializar cada linha
    for j in range (2):
        v = int(input(f" elemento[{i}][{j}]= "))
        linha.append(v)         # inserir cada  elemento na linha da matriz
    M.append(linha)             # acrescentar À matriz V a linha anterior
print(M)  # imprimir a matriz

 elemento[0][0]= 1
 elemento[0][1]= 2
 elemento[1][0]= 3
 elemento[1][1]= 4
[[1, 2], [3, 4]]


Gerar uma matriz V de 2X2 ,  de inteiros fornecidos pelo utilizador inserindo elemento a elemento:

In [11]:
L =[0]*2
print(L)

[0, 0]


In [4]:
M = [[0]*2,[0]*2]  #  gera  2 sublistas na lista com 2 elementos
print (M)

[[0, 0], [0, 0]]


In [7]:
M = [0]*2  #  gera  lista co 3 elementos a 0
for k in range(2): # criar na lista M 3 sublistas
    M[k] = [0]*2
print(M)
for i in range(2):           
    for j in range (2):
        v = int(input(f" elemento[{i}][{j}]= "))
        M[i][j]=v                # inserir cada  elemento na  matriz
print(M)                        # imprimir a matriz

[[0, 0], [0, 0]]
 elemento[0][0]= 2
 elemento[0][1]= 3
 elemento[1][0]= 4
 elemento[1][1]= 1
[[2, 3], [4, 1]]


Somar todos os elementos da matriz:

In [8]:
soma=0
for i in range(0,len(M)):
    soma+=sum(M[i])
print(soma)

10


Somar por linhas e apresentar a matriz e o resultado à frente de cada linha:

In [9]:
for i in range (0,len(M)):
    soma=0
    for j in range(0, len(M[i])):
        soma+=M[i][j]
        print(f"{M[i][j]:3d}",end="")
    print(f"\t{soma}")
    

  2  3	5
  4  1	5


Ordenar os elementos (em cada linha) usando o método `sort`

In [10]:
list.sort(M)
print(M)

[[2, 3], [4, 1]]


Suponha-se que se pretende encontrar a diagonal de uma matriz quadrada.

In [11]:
matriz=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
[matriz[i][i] for i in range(len(matriz))]

[1, 5, 9]

 No exemplo seguinte, apresenta-se uma definição por compreensão para transpor matrizes (embora esta operação seja disponibilizada em Python)

In [13]:
m=[[1, 2], [3, 4], [5, 6]]

In [14]:
[[linha[i] for linha in m] for i in range(len(m[1]))]

[[1, 3, 5], [2, 4, 6]]

Esta expressão constrói uma lista de listas. Para cada valor de `i`, constrói-se uma lista com as posições `i` de cada uma das linhas da matriz original (3), ou seja, com a coluna `i`. Os valores que `i` pode assumir correspondem ao comprimento das linhas, ou seja, ao número de colunas (2).

### <font color="CadetBlue"> A biblioteca NumPy</font> 
Em alternativa, o Python disponibiliza a biblioteca _`NumPy`_ com um conjunto de classes, variáveis de instância, métodos e funções que facilitam o cálculo algébrico com vetores e matrizes de várias dimensões, obtendo-se resultados com maior rapidez do que usando o listas. 

Portanto, o pacote NumPy, denominado dessa forma devido a abreviação de Numerical Python (Python Numérico), é uma biblioteca de código aberto destinada a realizar operações em arrays multidimensionais. O objeto array no NumPy é chamado `ndarray`, que fornece muitas funções de suporte que facilitam muito o trabalho  com arrays.
* O NumPy fornece uma excelente biblioteca para cálculos fáceis (em termos de escrita de código) e rápidos (em termos de velocidade).  
* O NumPy fornece algumas excelentes funções de biblioteca para rápida manipulação de imagens. Alguns exemplos são o espelhamento de uma imagem, a rotação de uma imagem por um determinado ângulo etc.  
* O NumPy possui também funções incorporadas para álgebra linear e geração de números aleatórios.  
* É uma biblioteca que pode ser usada em conjunto do `SciPy` e `MatPlotlib`, dois pacotes científicos para análise e visualização de dados.

Podes encontrar mais informação em: [W3Shools](https://www.w3schools.com/python/numpy/default.asp)


O NumPy pode ser instalado com `pip`, no comando no shell com a instrução:

```pip install numpy```
ou na distribuição anaconda, com a instrução: 
```conda install numpy```


In [15]:
import numpy as np
# gerar um array (vetor) de 2x3 preenchido com o valor zero
x = np.zeros((2, 3)) 
print (x)

[[0. 0. 0.]
 [0. 0. 0.]]


Criar um **array unidimensional (vetor)** com os valores 1, 2, 3, 4 e 5:

In [16]:
import numpy as np                   # importar a biblioteca numpy e todas as suas funcionalidades
V = np.array([1, 2, 3, 4, 5]) 
print(V)
print (type(V))              # verificar o tipo do objeto

[1 2 3 4 5]
<class 'numpy.ndarray'>


Criar um **array bidimensional (matriz)** com os valores 1, 2, 3 e 4, 5 e 6:

In [17]:
import numpy as np                   # importar a biblioteca numpy e todas as suas funcionalidades
M = np.array([[1, 2, 3],[4, 5, 6]]) 
print(M)

[[1 2 3]
 [4 5 6]]


Criar um **array tridimensional** com 2 arrays bidimensionais valores 1, 2, 3 e 4, 5 e 6:

In [18]:
import numpy as np               
Z = np.array([[[1, 2, 3],[4, 5, 6]],[[1, 2, 3],[4, 5, 6]]]) 
print(Z)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


**Alguns atributos e métodos mais usados em arrays:  **
(Supondo arr e arr2 arrays)

TIPO | UTILIZAÇÃO | Sintaxe  
:-------- | :--------: | :--------  
atributo ndim | verifica a dimensão do array | arr.ndim  
atributo ndmin | definir a dimensão do array | ndmin=<numero>  
    propriedade dtype | devolve o tipo de dados no array | arr.dtype  
    método copy | copiar o array arr para arr2| arr2=arr.copy() 
    método view | cria uma visualização do array arr em arr2 | arr2=arr.view()  
    atributo shape | dá-nos a forma do array (linas, colunas,...) | arr.shape  
    método sort | ordena os elementos do array | np.sort(arr)  
    método where | Devolve o índice do valor dado como parâmetro | x=np.where(arr == <valor>)
    
    


In [19]:
V = np.array([1, 2, 3, 4, 5]) 
print("Dimensão: ",V.ndim)
Z = np.array([1, 2, 3, 4], ndmin=3)
print(Z)
print ("Dimensão: ",Z.ndim)

Dimensão:  1
[[[1 2 3 4]]]
Dimensão:  3


**Acesso aos elementos de um array**  
O procedimento é o mesmo que o efetuado para acesso a elementos de uma lista.

In [20]:
A = np.array([1, 2, 3, 4])
print(A[1])
print (A[1]+A[3])

B=np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print("2.ª linha da 1.ª coluna: ", B[1,0]) # <---


2
6
2.ª linha da 1.ª coluna:  5


Para aceder a um elemento de um array. a partir do fim usar índices negativos (como para as listas):

In [21]:
A = np.array([1, 2, 3, 4])
print(A[-2])

3


#### <font color="DarkSlateGray">Fatiar (slicing) arrays</font>
Podemos definir qual a "fatia" de elementos de um array que pretendemos, indicando o índice inicial e final e ainda o step (tal como nas listas):  
[start:end:step]

In [22]:
A = np.array([1, 2, 3, 4, 5, 6, 7])
print(A[1:5:2])
print(A[::2])

[2 4]
[1 3 5 7]


In [23]:
M = np.array([[1, 2, 3, 4, 5, 6],[3, 4, 5, 6, 7, 8]])
print(M[0, 1:4],"\t", M[1,::2])

[2 3 4] 	 [3 5 7]


**Lista de todos os tipos de dados em NumPy**

i - integer  
b - boolean  
u - unsigned integer  
f - float  
c - complex float  
m - timedelta  
M - datetime  
O - object  
S - string  
U - unicode string  
V - pedaço fixo de memória para outro tipo ( void )  

Exemplo: Criar um array com dados do tipo inteiro de 4 bytes:

In [24]:
A = np.array([1, 2, 3, 4, 5, 6, 7], dtype='f4')
print(A)
print(A.dtype)

[1. 2. 3. 4. 5. 6. 7.]
float32


**Métodos copy e view**

In [25]:
import numpy as np

A = np.array([1, 2, 3, 4, 5])

x = A.copy()
y = A.view()
print(x)
print(y)

[1 2 3 4 5]
[1 2 3 4 5]


oedenar um array com a função `sort`

In [26]:
fruta = np.array(['banana', 'cereja', 'melão'])

print(np.sort(fruta))

['banana' 'cereja' 'melão']


Encontrar o índice para o valor especificado (método ` where()` ):

In [27]:
A = np.array([1, 2, 3, 4, 3, 5])

x = np.where(A == 2)
print(x)
x = np.where(A == 3)
print(x)
x = np.where(A == 7)
print(x)

(array([1], dtype=int64),)
(array([2, 4], dtype=int64),)
(array([], dtype=int64),)


 #### <font color="DarkSlateGray">Gerar números aleatórios</font>
A biblioteca NumPy disponibiliza o módulo `random` para trabalhar com números aleatórios.
**Exemplos:**

In [28]:
# gerar um número inteiro aleatório entre 0 e 100, inclusive.
from numpy import random
x = random.randint(100)
print(x)

53


In [29]:
# gerar um número real aleatório entre 0 e 1, inclusive.
from numpy import random
x = random.rand()
print(x)

0.9928100148588389


In [30]:
# gerar um array (vetor) de 5 números inteiros aleatórios entre 0 e 100, inclusive.
from numpy import random
x = random.randint(100, size=(5))
print(x)

[94 83 65  3 58]


In [31]:
# gerar um array (matriz) de 3x5 números inteiros aleatórios entre 0 e 100, inclusive.
from numpy import random
x = random.randint(100, size=(3,5))
print(x)

[[16 13 21  2 94]
 [63 53 99 23 72]
 [76  3 44 90 12]]


In [32]:
# gerar um array (vetor) de 5 números reais aleatórios entre 0 e 1, inclusive.
from numpy import random
x = random.rand(5)
print(x)

[0.43413539 0.21441121 0.70307328 0.816486   0.51796933]


In [33]:
# gerar um array (matriz) de 5x2 números reais aleatórios entre 0 e 1, inclusive.
from numpy import random
x = random.rand(5,2)
print(x)

[[0.94202348 0.40795774]
 [0.04260541 0.20192741]
 [0.55812448 0.39378   ]
 [0.03440783 0.63908109]
 [0.85509283 0.49910577]]


 #### <font color="DarkSlateGray">Executar cálculos matemáticos com Arrays NumPy</font>  
**Exemplos:**

In [34]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 1], [1, 1]])
s = A + B # Soma
sub = A - B # Subtração
p = A * B # Multiplicação
q = A / B # Divisão
print('Soma = \n', s)
print('\n')
print('Difference = \n', sub)
print('\n')
print('Product = \n',  p)
print('\n')
print('Quotient = \n', +q)


Soma = 
 [[2 3]
 [4 5]]


Difference = 
 [[0 1]
 [2 3]]


Product = 
 [[1 2]
 [3 4]]


Quotient = 
 [[1. 2.]
 [3. 4.]]


**Nota:** o operador de multiplicação executa a multiplicação por elementos.  
Para executar a <u>multiplicação de array</u>. utiliza-se a função `dot `:




In [35]:
matriz_produto = A.dot(B) 
print('Matriz produto = \n', + matriz_produto)

Matriz produto = 
 [[3 3]
 [7 7]]


## Bibliografia
Caleiro.C., Ramos.J.(2016). NB03 - Listas e outros tipos iteraveis. Dep. Matemática - IST.Lisboa:IST  
Vasconcelos, J. (2015).Python - Algoritmia e Programação Web. Lisboa:FCA  
Matthes. E.(2019). Python Crash Course - A Hands-On, Project-Based Introduction to Programming. San Francisco: USA  
https://docs.python.org/pt-br/3/contents.html  
https://medium.com/ensina-ai/entendendo-a-biblioteca-numpy-4858fde63355
https://www.w3schools.com/python/numpy/default.asp
https://www.w3resource.com/numpy/array-creation/arange.php
https://www.w3resource.com/numpy/manipulation/reshape.php  
Carvalho. Adelaide. (2021). Práticas de Python - Algoritmia e programação. Lisboa: FCA

<p ><img style="float:left" src="logo-poch2.png"></p> 